### ISSUE TITLE
Add Fallback for PEGTL Version Checking

### ISSUE THREAD

**Issue by rspavel** [quinoacomputing/cmake-modules#8]
It appears that older versions of PEGTL lack a version number in the source. Decide if it is better to keep the current fatal error or to comb the PEGTL history to see what the maximum version could be and report that instead.

**Comment by jbakosi** [comment]
While older PEGTL versions most likely lack a version number in the source, that is NOT why https://travis-ci.org/quinoacomputing/quinoa/builds/247979770 fails. Here is a snippet from the gentoo buildenv log that built the gentoo image the above build uses:

 > Emerging (8 of 21) dev-libs/pegtl-2.0.0::gentoo

Also note that the file `version.hpp` does exist inside the image:
```
$ docker run -ti quinoacomputing/buildenv:gentoo
sh-4.3$ ls -l /usr/include/tao/pegtl/version.hpp
-rw-r--r-- 1 root root 372 May 18 19:04 /usr/include/tao/pegtl/version.hpp
```
